
stages:
  - deploy

variables:
  POSTGRES_IP: $POSTGRES_IP
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_PORT: $POSTGRES_PORT

  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: $JWT_ACCESS_TOKEN_EXPIRE_MINUTES
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: $JWT_REFRESH_TOKEN_EXPIRE_DAYS
  JWT_ALGORITHM: $JWT_ALGORITHM

  DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE

  EMAIL_HOST_USER: $EMAIL_HOST_USER
  EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD


deploy-job:
  stage: deploy
  image: docker:20.10.17
  tags:
    - books_api
  before_script:
    - cp $ENV_FILE .env
  script:
    - docker compose -f ./docker-compose_prod.yml up --build
