version: '3.3'

services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    expose:
      - 5432
    ports:
      - "5433:5432"
    env_file:
      - ".env"

  django:
    container_name: django
    build: ./books_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./books_app:/books_app
    env_file:
      - ".env"
    depends_on:
      - postgres
