version: '3.3'

services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    expose:
      - 5432
    ports:
      - "5433:5432"
    env_file:
      - ".env"

  redis:
    image: redis:7.0
    container_name: redis
    expose:
      - 6379

  celery:
    build: ./books_app
    command: celery -A api.celery worker -l info
    volumes:
      - ./books_app/:/usr/src/app/
    env_file:
      - ".env"
    depends_on:
      - redis

  django:
    container_name: django
    build: ./books_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./books_app:/books_app
    env_file:
      - ".env"
    depends_on:
      - postgres
      - redis
