# Generated by Django 4.0 on 2022-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password_hash',
            field=models.CharField(default=None, max_length=256, verbose_name='Хеш пароля'),
        ),
    ]
