# Generated by Django 4.0 on 2022-08-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password_hash',
            field=models.CharField(max_length=256, verbose_name='Хеш пароля'),
        ),
    ]
