# Generated by Django 4.0 on 2022-08-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_author_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='UUID')),
                ('type', models.SmallIntegerField(choices=[(0, 'access'), (1, 'refresh')], default=0, verbose_name='Тип (0 - acccess/ 1 - refresh)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
