# Generated by Django 4.0 on 2022-08-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
