# Generated by Django 4.0 on 2022-08-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='uuid',
        ),
        migrations.AddField(
            model_name='token',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.TextField(default=None, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
