# Generated by Django 4.0 on 2022-08-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_token_uuid_token_id_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(default=None, unique=True, verbose_name='Токен'),
        ),
    ]
