# Generated by Django 4.0 on 2022-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_email_alter_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Отчество'),
        ),
    ]
