# Generated by Django 4.0 on 2022-08-26 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_confirmcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True,
                                        serialize=False, verbose_name='Идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
